version: 2

sources:
  - name: test_schema
    database: ALISHER_TEST_DB
    schema: ALISHER_TEST_SCHEMA
    tables:
      - name: USERS

models:
  - name: users_cleaned
    description: "Cleaned users table"
    time_spine:
      standard_granularity_column: birthdate
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: name
      - name: email
        tests:
          - not_null
          - unique
      - name: birthdate


  - name: user_statistics
    description: "User statistics"
    columns:
      - name: total_users
        tests:
          - not_null
      - name: youngest_user
      - name: oldest_user

